#!/usr/bin/env python

import subprocess
import shlex
import sys
import os


def main(arg=['']):
    pwd = os.getcwd()
    c = "docker run -it --name dim --rm -v {}:/home/editor/src usagikeri/docker-vim {}".format(pwd, " ".join(arg))
    subprocess.call(shlex.split(c))


if __name__ == '__main__':
    try:
        args = sys.argv[1:]
        main(args)
    except IndexError:
        main()
    except Exception as e:
        print(e)
